# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
