# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galerija', '0002_slika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='photos/%Y/%m')),
                ('is_cover_photo', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Slika',
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='picture',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerija.Album'),
        ),
        migrations.AddField(
            model_name='picture',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
