# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerija', '0003_auto_20170105_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(default='timezone.now', max_length=100),
        ),
    ]
