# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galerija', '0004_picture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
