# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerija', '0010_auto_20170113_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-pub_date']},
        ),
    ]
