# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galerija', '0011_auto_20170113_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='naslovnaSlika',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
