# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerija', '0013_remove_picture_is_cover_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-pubDate']},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-pubDate']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='pub_date',
            new_name='pubDate',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='pub_date',
            new_name='pubDate',
        ),
    ]
